version: '3'

services:
  app:
    restart: always
    build:
      context: .
    ports:
      5000:5000
    volumes:
      ./app.py:/app/app.py
    image: 
      parakulsu/tars:v1

    command: python /app/app.py